// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AI9DPValB8Ns1SHnXFiJgi4IxlVkd5Q',
    appId: '1:922074558420:web:8100b1c16f7ebee88ab041',
    messagingSenderId: '922074558420',
    projectId: 'music-player-cf155',
    authDomain: 'music-player-cf155.firebaseapp.com',
    storageBucket: 'music-player-cf155.firebasestorage.app',
    measurementId: 'G-6DJKR82ELJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbuYo7HFvzFI54btD0lUwyFn4K9_SVVqU',
    appId: '1:922074558420:android:e7c4b33a76e553d68ab041',
    messagingSenderId: '922074558420',
    projectId: 'music-player-cf155',
    storageBucket: 'music-player-cf155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWF9C4dqLgfmrfzj7cekqpzyHPi2b3dsw',
    appId: '1:922074558420:ios:76ea1318444a9f2b8ab041',
    messagingSenderId: '922074558420',
    projectId: 'music-player-cf155',
    storageBucket: 'music-player-cf155.firebasestorage.app',
    iosBundleId: 'com.example.musicappTrav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWF9C4dqLgfmrfzj7cekqpzyHPi2b3dsw',
    appId: '1:922074558420:ios:76ea1318444a9f2b8ab041',
    messagingSenderId: '922074558420',
    projectId: 'music-player-cf155',
    storageBucket: 'music-player-cf155.firebasestorage.app',
    iosBundleId: 'com.example.musicappTrav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4AI9DPValB8Ns1SHnXFiJgi4IxlVkd5Q',
    appId: '1:922074558420:web:eb7e9d83a54dbfa48ab041',
    messagingSenderId: '922074558420',
    projectId: 'music-player-cf155',
    authDomain: 'music-player-cf155.firebaseapp.com',
    storageBucket: 'music-player-cf155.firebasestorage.app',
    measurementId: 'G-GXT1Y5QT7T',
  );
}
